#!/bin/bash
new="<<<Create New>>>";
entries=`ls $HOME/.config/google-chrome-app/`;
profile=`echo -e "$new\n$entries" | zenity --list --column "Profile" --height 400 --title "chrome-profiles" --text "Select a profile to launch:"`
if [[ "$profile" ]]; then
	if [[ "$profile" == "$new" ]]; then
		profile=`zenity --entry --title "chrome-profiles" --text "Enter a new profile name:"`;
		if [[ "$profile" ]]; then
			echo "Creating $profile...";
			if [ ! -d "$HOME/.config/google-chrome-app/$profile" ]; then
				cp -r $HOME/.config/google-chrome-app/skeleton "$HOME/.config/google-chrome-app/$profile"
			fi
		else
			exit 1;
		fi;
	fi;
	echo "Selected profile: $profile.";
	google-chrome "--app=$profile" --restore-last-session "--user-data-dir=$HOME/.config/google-chrome-app/$profile"
else
	echo "No profile selected.";
	exit 1;
fi;