#!/bin/bash
# Created by bas v0.5

source ~/bin/jobs

function help {
cat <<EOF
$(basename ${0}) v0.3 - Start Google Chrome with the selected/new profile

Usage:
    $(basename ${0})

Dependencies:
    zenity
    google-chrome
    dmenu

EOF
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    help;
    exit 1;
fi;

function main {
	new="<<<Create New>>>";
	configdir=${HOME}/.config/google-chrome-profiles/
	entries=$(ls -1 ${configdir});
#	profile=$(echo -e "${new}\n${entries}" | zenity --list --column "Profile" --hide-header --height 400 --title "chrome-profiles" --text "Select a profile to launch:" --print-column=1)
	profile=$(echo -e "${new}\n${entries}" | dmenu -b -l 5 -p "Select a profile to launch:")
	if [[ "${profile}" ]]; then
		if [[ "${profile}" == "${new}" ]]; then
			profile=$(zenity --entry --title "chrome-profiles" --text "Enter a new profile name:");
			if [[ "${profile}" ]]; then
				echo "Creating ${profile}...";
				if [ ! -d "${configdir}${profile}" ]; then
					cp -r ${configdir}skeleton "${configdir}${profile}"
				fi
			else
				exit 1;
			fi;
		fi;
		echo "Selected profile: ${profile}.";
		google-chrome "--app=${profile}" --restore-last-session "--user-data-dir=${configdir}${profile}"
	else
		echo "No profile selected.";
		exit 1;
	fi;
}

main "$@";
